import { Template } from "./template-types";

export const SEED_TEMPLATES: Template[] = [
  {
    id: `tpl_001`, name: `店铺推荐文案`, description: `口碑推荐型店铺简介`,
    angle: `口碑推荐`, format: `单篇详评`,
    structure: [`钩子`, `主体`, `总结`],
    hook: `问题式`, tone: [`专业`, `亲切`],
    cuisines: [`all`],
    platforms: [`dianping`],
    stages: [`early`, `growth`, `mature`],
    promptTemplate: `以老顾客口吻推荐这家店`,
    weight: 0.85,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_002`, name: `菜品深度介绍`, description: `突出食材/工艺的菜品描述`,
    angle: `单品深挖`, format: `列表体`,
    structure: [`食材`, `工艺`, `口感`, `推荐`],
    hook: `直白式`, tone: [`专业`, `温暖`],
    cuisines: [`all`],
    platforms: [`dianping`, `xiaohongshu`],
    stages: [`early`, `growth`, `mature`],
    promptTemplate: `详细描述菜品的食材、制作工艺和口感体验`,
    weight: 0.72,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_003`, name: `探店打卡笔记`, description: `场景式小红书打卡内容`,
    angle: `场景打卡`, format: `合集体`,
    structure: [`环境`, `菜品`, `价格`, `总结`],
    hook: `悬念式`, tone: [`活泼`, `亲切`],
    cuisines: [`all`],
    platforms: [`xiaohongshu`],
    stages: [`growth`, `mature`],
    promptTemplate: `以探店视角写出真实体验感`,
    weight: 0.68,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_004`, name: `美食真实分享`, description: `真实体验型种草笔记`,
    angle: `真实体验`, format: `单篇详评`,
    structure: [`起因`, `经过`, `结果`, `建议`],
    hook: `故事式`, tone: [`亲切`, `文艺`],
    cuisines: [`all`],
    platforms: [`xiaohongshu`],
    stages: [`early`, `growth`],
    promptTemplate: `用真实食客口吻写一次就餐体验`,
    weight: 0.55,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_005`, name: `抖音短视频脚本`, description: `吸引停留的短视频剧本`,
    angle: `故事叙述`, format: `脚本体`,
    structure: [`3秒钩子`, `内容`, `翻转`, `引导`],
    hook: `悬念式`, tone: [`活泼`, `幽默`],
    cuisines: [`all`],
    platforms: [`douyin`],
    stages: [`early`, `growth`, `mature`],
    promptTemplate: `写出一个让用户停留观看的短视频脚本`,
    weight: 0.78,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_006`, name: `口播引流文案`, description: `短平快口播类内容`,
    angle: `好奇引流`, format: `口播体`,
    structure: [`提问`, `回答`, `行动引导`],
    hook: `问题式`, tone: [`亲切`, `直接`],
    cuisines: [`all`],
    platforms: [`douyin`],
    stages: [`early`, `growth`],
    promptTemplate: `用口播方式直接与观众对话`,
    weight: 0.62,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_007`, name: `节日活动方案`, description: `节日节气营销活动`,
    angle: `节日营销`, format: `海报体`,
    structure: [`活动主题`, `优惠内容`, `参与方式`, `限时提醒`],
    hook: `直白式`, tone: [`活泼`, `温暖`],
    cuisines: [`all`],
    platforms: [`dianping`, `xiaohongshu`, `wechat`],
    stages: [`growth`, `mature`],
    promptTemplate: `设计一个有吸引力的节日促销活动`,
    weight: 0.65,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
  {
    id: `tpl_008`, name: `新客优惠文案`, description: `吸引新用户到店`,
    angle: `优惠引流`, format: `通知体`,
    structure: [`福利`, `条件`, `行动引导`],
    hook: `直白式`, tone: [`亲切`, `直接`],
    cuisines: [`all`],
    platforms: [`dianping`, `xiaohongshu`, `douyin`],
    stages: [`early`],
    promptTemplate: `用优惠信息吸引新客户到店消费`,
    weight: 0.58,
    status: `active`, createdAt: `2026-07-24`,
    storeWeightOffsets: {}, usageCount: 0, skipCount: 0,
  },
];
